### ISSUE TITLE
Upgrade samples dependencies management

### ISSUE THREAD

**Issue by ch4mpy** [spring-projects-experimental/spring-native#1045]
A few points I noted in samples maven dependencies management:
- samples still point to `0.10.0.3-SNAPSHOT`
- `spring-boot-starter-web` is frequently referenced with exclusion of tomcat and explicit additional dependency to `tomcat-embed-programmatic`, which doesn't seem necessary any-more
- pom.xml locations do no reference samples modules directory tree
- parent poms do not list modules, which makes it more complicated to build all samples (for instance to tests global non regression after a version change in parent)
- spring-cloud version happens to be both managed in parent pom and hard-coded in child module

**Comment by sdeleuze** [comment]
Hey @ch4mpy, 

Wrong samples parent pom is now fixed by a557729fb55ce5825f316088d90c44aa0cc8b46a and Spring Cloud duplicated version management by 88e1154c80c223dc0132680f26d8cdda5dceafd6.

`tomcat-embed-programmatic` and Tomcat exclusion is still needed for optimal footprint.

For other changes, I prefer to skip for now since `build.sh` are used to build all the samples (maven and Gradle), I think that's best practice to reference the parent pom location when not in the parent directory and since we are currently doing a huge refactoring on `0.11.x` branch which should be merged shortly on `main` so I want to avoid complex conflicts to merge.

Thanks for raising that issue.
