### ISSUE TITLE
Please add type hints for Reactor's `Traces` class

### ISSUE THREAD

**Issue by joshlong** [spring-projects-experimental/spring-native#1098]
Reactor's `Traces` reflectively instantiates [three types ](https://github.com/reactor/reactor-core/blob/main/reactor-core/src/main/java/reactor/core/publisher/Traces.java#L54) in its `Traces` class which breaks in a native context. Please register hints for them. I'll file an issue asking them to please kindly consider changing those to `.class` literals insted of strings, for the future. I think that should fix things, right?

**Comment by sdeleuze** [comment]
Done, please let me know if that does not work as expected. I don't think changing to `.class` would be enough since that will only bring access to the class not the constructor.

We are working on better inlining when constants are used with GraalVM team, that could help. For now those hints are good enough IMO.

**Comment by joshlong** [comment]
thank you!
