### ISSUE TITLE
Add getSpringFactoriesInstances override to ModifiedSpringApplicationContributor

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#1102]
See 94c7e33f351a9b489ff7aaaf8627c95fd41a6c2b related commit.

**Comment by aclement** [comment]
There are trade offs here with the kinds of patching we are doing. Due to modifying just the pieces of bytecode we need, rather than just writing out completely new method contents we may continue to operate successfully even when the incoming SpringApplication from Spring itself is updated. However, the way we are doing it is very sensitive to certain things, for example if the compiler chose to store state in different local variables on a particular run, we may break. I think if this general approach proves to be useful and is likely to hang around for a while we should review the robustness (maybe before 0.11 final goes out).   The alternative would be just patching in the whole method like the substitutions do, but then you lose any changes in the incoming code.

What we could actually do is implement a very lightweight build time version of substitutions.  In theory we could copy the exact content of the methods marked `@Substitution` in the `Target_SpringApplication` and drop them into the `SpringApplication` methods. This would ensure there is no need to keep changing ModifiedSpringApplicationContributor, it would also be in step.
