### ISSUE TITLE
Reflection hint declared on bean definition type are not usable on bean implementation

### ISSUE THREAD

**Issue by christophstrobl** [spring-projects-experimental/spring-native#1121]
In case a `destroy` method is registered for an interface the actual invocation of that method on the concrete bean type fails due to missing reflection configuration for the implementation class.

This can be seen when shutting down the _data-mongodb_ sample.

_Bean name:_ "mongo",
_Bean type:_ `MongoClient` (extends `Closeable`)

the resulting reflection configuration holds the entry for the client

```json
{
  "name": "com.mongodb.client.MongoClient",
  "methods": [
    {
      "name": "close",
      "parameterTypes": []
    }
  ]
},
```

On shutown `InitDestroyBeanPostProcessor` receives the actual `MongoClient` implementation `com.mongodb.client.internal.MongoClientImpl` for which no reflection entry is available resulting in an NPE.

```bash
o.s.a.c.a.InitDestroyBeanPostProcessor   : Invoking destroy method on bean 'mongo': null
o.s.a.c.a.InitDestroyBeanPostProcessor   : Failed to invoke destroy method on bean with name 'mongo'

java.lang.NullPointerException: null
	at org.springframework.util.ReflectionUtils.makeAccessible(ReflectionUtils.java:571) ~[na:na]
	at org.springframework.aot.context.annotation.InitDestroyBeanPostProcessor.invokeMethod(InitDestroyBeanPostProcessor.java:121) ~[na:na]
	at org.springframework.aot.context.annotation.InitDestroyBeanPostProcessor.invokeDestroyMethod(InitDestroyBeanPostProcessor.java:95) ~[na:na]
	at org.springframework.aot.context.annotation.InitDestroyBeanPostProcessor.postProcessBeforeDestruction(InitDestroyBeanPostProcessor.java:85) ~[na:na]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:184) ~[na:na]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:587) ~[na:na]
```

If we keep track of the type used in the bean definition we could lookup the method on that one and do the invocation on the instance which works fine when I gave it a spin.

```
o.s.a.c.a.InitDestroyBeanPostProcessor   : Invoking destroy method on bean 'mongo': public abstract void com.mongodb.client.MongoClient.close()
```

**Comment by snicoll** [comment]
It turns out that we're doing more work than we should. `DisposableBeanAdapter` is already taking care of `AutoCloseable` and friends so there's no need to process `(inferred)` destroy method name.

However, we need to process them for reflection configuration purposes so we'll have to retain that information somehow.

**Comment by snicoll** [comment]
And I take that back. `DisposableBeanAdapter` does this based on the fact the `BeanDefinition` has an inferred destroy method name but we're not writing that back since we're handling it ourselves (discovering the method to call at runtime).

**Comment by snicoll** [comment]
Let's fix this one separately. The problem is that we add a reflection hint for `MongoClient` (the interface) and, at runtime, we ask for a method based on the actual bean instance type (that implements `MongoClient`). 

GraalVM is quite picky there and we have to ask the method on the interface type. Unfortunately, `ReflectionUtils` only look for super classes (and not interface) because that's all that's needed on a regular JVM.

I'll fix this by doing an extra check based on the bean definition type as it should give the same behavior as the one used to register the reflection entry.

**Comment by snicoll** [comment]
AutoCloseable is going to be handled in #1124
