### ISSUE TITLE
Resource loader does not recognize URL resource

### ISSUE THREAD

**Issue by eleftherias** [spring-projects-experimental/spring-native#1147]
When calling `DefaultResourceLoader#getResource` with a URL, e.g `"https://site.com"`, it should return an object with type `org.springframework.core.io.UrlResource`.
However, in native mode, it returns an object with type `org.springframework.core.io.DefaultResourceLoader$ClassPathContextResource`.

Demo: https://github.com/eleftherias/resource-loader-native
The demo prints the class name returned by `getResource` when called with a URL.
Using GraalVM 21.2.0 (build 11.0.12+6-jvmci-21.2-b08).

**Comment by sdeleuze** [comment]
You need to add `--enable-https` (or `--enable-http` if the URL has http protocol) to make it work as expected. Could be initially surprising but I think this is the expected behavior. here I used `@NativeHint(options = "--enable-https")` but you can maybe update Spring Native hints for related use cases. Feel free to comment if you need additional guidance/feedback.
