### ISSUE TITLE
Upgrade to native build tools 0.9.7.1

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#1202]
Spring Boot 2.6.0-RC1 is based on JUnit 5.8.1, so it should be fine.

I did a quick try, upgrading to 0.9.7.1, adding `<extensions>true</extensions>` in Maven `pom.xml` and removing `junit-platform-native` dependency, but I got the following failure message.

> Test configuration file wasn't found. Make sure that test execution wasn't skipped.

As pointed out in https://github.com/spring-projects-experimental/spring-native/issues/1192#issuecomment-956214014, `org.junit.platform.launcher.TestIdentifier` build-time initialization configuration should be removed from `SpringBootTestHints`.

Could you please take care of that @sbrannen?

**Comment by sbrannen** [comment]
> Test configuration file wasn't found. Make sure that test execution wasn't skipped.

This happens because the version of Maven Surefire in use is using an older version of the `junit-platform-launcher` artifact that does not contain the `UniqueIdTrackingListener` that was introduced in JUnit 5.8 (JUnit Platform 1.8).

There are two ways to _fix_ this.

1. Declare an explicit test-scoped dependency on the `junit-platform-launcher` artifact (see below).
2. Upgrade to Maven Surefire 3.0.0-M5 as used in the sample applications in the Native Build Tools project.

**Comment by sbrannen** [comment]
Note that the auto-alignment of JUnit Platform versions was added in Maven Surefire 3.0.0-M4 (https://issues.apache.org/jira/browse/SUREFIRE-1585).

**Comment by sbrannen** [comment]
Superseded by #1206
