### ISSUE TITLE
Add more test use cases in samples

### ISSUE THREAD

**Issue by snicoll** [spring-projects-experimental/spring-native#1241]
To confirm that the aot generation works properly, we should add more testing use cases to our samples.

* Servlet-based test with a random port and a `TestRestTemplate`
* Servlet-based mock test (regular `@SpringBootTest`)  with the MockMvc support
* WebFlux-based test with a random port and a `WebTestClient`
* Webflux-based mock test (regular `@SpringBootTest`)  with the WebTestClient mock support
* One occurrence of each of the slice tests we have
* A test that's customizing the environment

There are probably more use cases we'd like to cover. Essentially what `@SpringBootTest` can do and the various `TestExecutionListeners` that should be applied. Most of it should be added in existing samples probably but we may also create a dedicated sample if we have to.

**Comment by snicoll** [comment]
What is remaining here?

**Comment by ttddyy** [comment]
The tests I wrote covers:

- Servlet-based test with a random port and a TestRestTemplate  
  -  `RandomPortTests` in webmvc-tomcat
- Servlet-based mock test (regular @SpringBootTest) with the MockMvc support  
  - `WebmvcControllerMockTests` in webmvc-tomcat
- WebFlux-based test with a random port and a WebTestClient
  - `RandomPortTests` in webflux-netty
- Webflux-based mock test (regular @SpringBootTest) with the WebTestClient mock support
  - `RandomPortTests` in webflux-netty
- A test that's customizing the environment
  - `RandomPortTests` in webmvc-tomcat

> - One occurrence of each of the slice tests we have

Currently these slice annotations are covered:
- `@RestClientTest`
  - `RestTemplateClientServiceTests` in boot-features
- `@WebFluxTest`
  - `WebfluxSliceTests` in webflux-netty
- `@WebMvcTest`
  - `WebmvcSliceTests` in webmvc-tomcat
- `@JsonTest`
  - `RequestJsonTests` in webmvc-tomcat
  - NOTE: currently disabled due to gh-1292
- `@JdbcTest`
  - `SampleJdbcTests` in spring-aot-test


These are the slice annotations that I don't find corresponding dedicated tests:
- `@DataCassandraTest`
- `@DataJdbcTest`
- `@DataJpaTest`
- `@DataLdapTest`
- `@DataMongoTest`
- `@DataNeo4jTest`
- `@DataR2dbcTest`
- `@DataRedisTest`
- `@JooqTest`
- `@WebServiceClientTest`

**Comment by snicoll** [comment]
For the record, I have restored JsonTest as I believe I've fixed the related issue.

**Comment by sdeleuze** [comment]
Let's go with what we have for 0.11.0.
