### ISSUE TITLE
Liveness and readiness probes not exposed in Kubernetes

### ISSUE THREAD

**Issue by dsyer** [spring-projects-experimental/spring-native#1274]
With the `actuator-webmvc` sample:

```
$ kubectl describe pod app-58d5659b99-2psd5 
...
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
...
  Warning  Unhealthy  30s (x3 over 36s)  kubelet            Liveness probe failed: Get "http://10.244.0.12:808/actuator/health/liveness": dial tcp 10.244.0.12:808: connect: connection refused
...
```

**Comment by snicoll** [comment]
This is working as expected as all the conditions are evaulated at build time at the moment. We're going to improve the doc as part of #1278

**Comment by dsyer** [comment]
But this sample has `management.endpoint.health.probes.enabled=true` in `application.properties`. So it should be unconditionally exposed right? I'm not sure I understand, but it still seems like a bug to me.

**Comment by bclozel** [comment]
Liveness and Readiness probes are not enabled by default in Spring Boot, they're really enabled depending on the Cloud Platform (see spring-projects/spring-boot#22825). As Stephane said, conditions are evaluated at build time (for now) and without a configuration property set, I believe this is the expected behavior. That's a behavior we want to fix in the future, but it's just not possible in the context of Spring Native as it requires deeper integration with Spring Framework.

**Comment by snicoll** [comment]
> But this sample has management.endpoint.health.probes.enabled=true in application.properties

We can't really triage an issue reliably if you provide mixed information. There's "automatically in Kubernetes" in the title and it's hard to not think about what Brian and I just mentioned.

**Comment by bclozel** [comment]
Don't we need `management.health.livenessstate.enabled=true` in this case as well?

**Comment by mhalbritter** [comment]
This is obsolete, it works now. When adding 

```
management.endpoint.health.probes.enabled=true
```

in the `application.properties`, the native application exposes the readiness and liveness states.
