### ISSUE TITLE
Please add a `@TypeHint` for `JwtDecoder.class` for Spring Security's hints 

### ISSUE THREAD

**Issue by joshlong** [spring-projects-experimental/spring-native#1377]
The class is used reflectively in the bowels of Spring Security's OAuth / OIDC support and will stop the build from proceeding. 

see https://github.com/okta-samples/okta-spring-boot-sample/pull/27  for an example 

cc @mraible

**Comment by sdeleuze** [comment]
@eleftherias Could you please take care of this one?

Since non-annotation triggers now leverage static analysis capabilities, maybe something like `@NativeHint(trigger = JwtDecoder.class, types = @TypeHint(types = JwtDecoder.class))` will be enough. That said, worth to test it and analyze why it is needed.

**Comment by eleftherias** [comment]
I see the issue, looking into the best way to fix it now.
