### ISSUE TITLE
Native image not picking up JAVA_OPTS

### ISSUE THREAD

**Issue by the-verge** [spring-projects-experimental/spring-native#1439]
I have successfully built a native image using the spring-boot-maven-plugin. However, any options that I attempt to pass via JAVA_OPTS are not picked up when running the image and the app won't start.

I use a combination of ```@ConfigurationProperties``` and ```@Value``` to read whatever I pass in at runtime

### Plugin configuration
```
<configuration>
    <image>
        <builder>paketobuildpacks/builder:tiny</builder>
        <env>
            <BPE_DELIM_JAVA_TOOL_OPTIONS xml:space="preserve"> </BPE_DELIM_JAVA_TOOL_OPTIONS>
            <BPE_PREPEND_JAVA_TOOL_OPTIONS>-Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager</BPE_PREPEND_JAVA_TOOL_OPTIONS>
            <BP_NATIVE_IMAGE>true</BP_NATIVE_IMAGE>
            <BP_NATIVE_IMAGE_BUILD_ARGUMENTS>
                --verbose
                -H:+ReportExceptionStackTraces
            </BP_NATIVE_IMAGE_BUILD_ARGUMENTS>
        </env>
        <name>spring-native-application</name>
    </image>
    <excludes>
        <exclude>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </exclude>
    </excludes>
</configuration>
```
### Docker run command
```
docker run -it -p 8443:8443 --env JAVA_OPTS="-Dspring.profiles.active=xfac -Dabc=xyz ... " spring-native-application
```
Does a native image support consuming options like this? If not, how should this be done?

Also to note that I can build the same application as a non-native image using the spring-boot-maven-plugin, and all works as expected.

**Spring Boot 2.6.2**
**Spring Native 0.11.1**

**Comment by sdeleuze** [comment]
I don't think native image supports `JAVA_OPTS` ([native image](https://www.graalvm.org/reference-manual/native-image/) is documented here) because they are specific to `java` command line.

When using executables compiled with Native Build Tools, I usually uses [command line properties](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.external-config.command-line-args). For your Buildpacks use case, [binding from environment variables](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.external-config.typesafe-configuration-properties.relaxed-binding.environment-variables) is what I would propose.

Be aware that conditions are fixed at build time so just change properties that will not trigger new part of the infrastructure (new or different beans for example) otherwise that will not work. See [related commit](https://github.com/spring-projects-experimental/spring-native/commit/0f8588442bd30c77e9a3b4768cdb782676952f23).
