### ISSUE TITLE
Refine and optimize JPA/Hibernate support

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#144]
- Check if `hibernate-graalvm` is usable : my guess is that it is not because static config is not efficient enough in term of footprint but worth to check and we could maybe use its config to improve our compatibility
- Configure `hibernate.bytecode.provider=none` automatically
- Document usage of `hibernate-enhance-maven-plugin`
- Document limitations
- Fix martin-lizner  repro

**Comment by martin-lizner** [comment]
Upvoting this. Im unable to compile https://github.com/Evolveum/midpoint project due to hibernate error. Using 0.8.0 spring-graalvm and java11-20.2.0/bin/native-image on Linux. Thanks.

could not find target method: private void org.hibernate.jpa.boot.internal.Target_EntityManagerFactoryBuilderImpl.processHibernateConfigXmlResources(org.hibernate.boot.registry.StandardServiceRegistryBuilder,org.hibernate.jpa.boot.internal.Target_EntityManagerFactoryBuilderImpl$Target_MergedSettings,java.lang.String)
        at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findOriginalMethod(AnnotationSubstitutionProcessor.java:637)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleMethodInAliasClass(AnnotationSubstitutionProcessor.java:330)

**Comment by sdeleuze** [comment]
@martin-lizner Could you please provide a minimal repro for the issue you mentioned?

**Comment by sdeleuze** [comment]
As discussed with @schauder I will focus on reviewing the substitutions and him on the hints.

**Comment by sdeleuze** [comment]
@martin-lizner My recent commit should fix your issue.
