### ISSUE TITLE
Support @SpringBootConfiguration

### ISSUE THREAD

**Issue by SentryMan** [spring-projects-experimental/spring-native#1490]
So I'm trying to create a lambda with native image, but I'm forced to use @SpringBootApplication or else I get this error. `java.lang.IllegalStateException: java.lang.ClassNotFoundException: org.springframework.aot.ContextBootstrapInitializer`
It'd be pretty great to be able to use @SpringBootConfiguration for the cases when all the autoconfigs aren't needed.

**Comment by sdeleuze** [comment]
@bclozel @snicoll What behavior do you suggest for projects annotated with `@SpringBootConfiguration public class Application { }`?

Currently we only detect `@SpringBootApplication ` and skip AOT if not found in order to be lenient for non Spring Boot projects (on purpose) like in our `grpc` sample.

Happy to add special handling for project annotated with `@SpringBootConfiguration` (process it like `@SpringBootApplication`, throw an error or special handling).

**Comment by snicoll** [comment]
`SpringBootApplication` is meta-annotated with `SpringBootConfiguration`. From my perspective, even `Configuration` would be enough. Whether or not AOT processes auto-configuration is solely based on what the application class defines. It should be tested to validate something else doesn't break but there's no need to make that a special case IMO.
