### ISSUE TITLE
[BUG] Spring-Boot Actuator 2.7.1 loggers endpoint is not working with Spring Native 0.12.1

### ISSUE THREAD

**Issue by jdbcplusnet** [spring-projects-experimental/spring-native#1715]
I was trying to migrate Spring-Boot microservice to native, but I was some error with Spring-Boot-Actuator for get / change loggers in realtime.

The /actuator/loggers endpoint returns HTTP 500 error and I have created my own LoggerEndpoint for trying to solve this issue, but it seems that  the **org.springframework.boot.logging.logback.LogbackLoggingSystem** does not get loggers configuration properly so I got empty loggers:

![image](https://user-images.githubusercontent.com/74903597/190396053-d6d8b6a9-4876-43a3-a866-2f6950b19464.png)

This is because the method getLoggerConfigurations() from LogbackLoggingSystem is not working propertly:

![image](https://user-images.githubusercontent.com/74903597/190396424-59dffb32-4c19-401f-9ce3-6785e7ffd033.png)

Versions used as described in documentacion: https://docs.spring.io/spring-native/docs/current/reference/htmlsingle

- Spring-Boot 2.7.1
- Spring Native 0.12.1

![image](https://user-images.githubusercontent.com/74903597/190395515-b195d0f5-2d93-4c6d-9a28-899b77cae236.png)

Thanks in advance.

**Comment by sdeleuze** [comment]
On my side, I see a 404 error not a 500 one, but indeed it is broken. Since we are focusing on Spring Boot 3 native support these days, I have testing with Spring Boot 3 M5 and saw the same issue, so I have created https://github.com/spring-projects/spring-boot/issues/32483 that you can follow to track the resolution of this issue on Spring Boot 3 side (we won't fix it on Spring native side).
