### ISSUE TITLE
Move remaining static JSON configuration files to hints

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#216]
As a follow up of #215, we should move reflection and initialization config to the hints, and totally remove those static files and related processing mechanism to lower the maintenance cost and cognitive load. That would also allow more checks during compilation.

**Comment by aclement** [comment]
The systems are in place now to move 99% of stuff over (initialization/proxies/reflection/resources). I saw some specific members mentioned in the reflect-config for kotlin - individual members can now be specified in TypeInfo's now too.

**Comment by aclement** [comment]
I've now dropped in the Synthesized annotation computation stuff in as a component processor: https://github.com/spring-projects-experimental/spring-graalvm-native/blob/master/spring-graalvm-native-configuration/src/main/java/org/springframework/SynthesizerComputationComponentProcessor.java

This is enabling me to start deleting proxy entries from proxies.json if they are purely a type+SynthesizedAnnotation. The trouble is the current breakages around some samples due to Boot 2.4.0 snapshots is making it tricky to do full test verification runs.

**Comment by aclement** [comment]
Just to add - this should make us more robust in automatically handling types we haven't seen before in samples that need synthesized proxies.
