### ISSUE TITLE
Create proxies at build time

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#356]
In order to be able to support proxies on classes and to check if it avoids to reduce the footprint.

**Comment by richvim** [comment]
This is a blocker for our applications, so absolutely would love to see this feature added.

**Comment by leccelecce** [comment]
Is this task a solution to having to define values in proxy-config.json?

**Comment by chenzhiguo** [comment]
As far as I know, a large number of RPC frameworks use proxies, such as dubbo, will they support it?

**Comment by odrotbohm** [comment]
The path we ran into this being needed in the data work, was Spring MVC controllers used with Spring HATEOAS and pointing to controller methods to create links. That API creates proxies for controller classes to record the immediately following method invocation. A similar approach ist used by Spring MVC's `MvcUriComponentsBuilder`. I don't think we can reasonably ask users to introduce interfaces for all their controllers to make this work.

While Spring Data REST doesn't even use that feature in its own codebase, it's likely that users, that use it, do, because creating links between resources is a very core concept to APIs built with Spring Data REST and HATEOAS in particular.

**Comment by sdeleuze** [comment]
A sample that requires a class proxy for at least `AnagramHandler`, could be useful for testing : https://github.com/nekperu15739/anagram.

**Comment by aclement** [comment]
I'm not against that, just worry about the disruption. However I suppose  as we keep most references in this project, it isn't too bad. `JdkProxyHint` or` JdkDynamicProxyHint`. I suppose it impacts videos out there already and workshop materials, hmm. Is it that confusing, I'm not sure.

**Comment by sdeleuze** [comment]
Let's discuss that during next week meeting. We have warned users there will be breaking changes, with upgrade path.

**Comment by aclement** [comment]
Closing this to capture to work we have done in 0.10 - I will likely create a spin off for the `AnagramHandler` sample, I still want to explore that.
