### ISSUE TITLE
Provide plugin configuration properties

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#484]
If I specify ` -Dspring.native.remove-yaml-support=true` in `commandlinerunner`, `-H:+PrintAnalysisCallTree` shows Yaml classes are still included and `reflect-config.json` includes a `org.yaml.snakeyaml.Yaml` entry.

Maybe the switch to bti has broken `ConfigOptions` environnement based flag customomization?

**Comment by sdeleuze** [comment]
We could maybe set it automatically based on the presence of `application*.yml` and allow the user to override.

**Comment by aclement** [comment]
How are you setting it?  There are two stages to think about now
- if you want to influence .json computation, have to set it early.
- if you want it to influence substitutions, need to set it late.

'Early' currently means early early as in -D passed to the maven command, setting it in build.args is too late.  Setting it late means including it in build.args so that native-image will see it.

I originally allowed it to be set once in build.args in the pom.xml for a sample then my variant of `compileWithMaven.sh` (while we were getting it going in bti samples) would extract those settings from build.args, ensuring they are set early when calling the mvn command but when we refactored that from individual samples to the shared folder that special handling of build.args was deleted. This enabled you just to specify things once and be set for both places.

I then changed `compileWithMaven.sh` to include a `$*` parameter in the call to maven. This means samples could tweak their `build.sh` scripts to pass -D options through to the maven command line that were specific to that sample, but it looks like you thought it was a typo and deleted it? So now I have no way to pass options to the maven command from individual samples. (i.e. with $* I could put this in `build.sh` and it would work fine):

```
${PWD%/*samples/*}/scripts/compileWithMaven.sh -Dspring.native.remove-yaml-support=true && ${PWD%/*samples/*}/scripts/test.sh
```

Both of the actuator samples were using this ability because they are experimenting with settings that reduce the footprint, but now the extra -D they specify in the build.sh scripts don't work.

The short term fix would be to put the $* back in, but of course specifying things in multiple places is a pain.

The total right thing to do here (I think) is for the maven plugins to offer real configuration settings we can then set via configuration in the XML, then build.args could also be used there I think.

This will build command line runner with no Yaml in the .json:
```
mvn -Dspring.native.remove-yaml-support=true -e -ntp -Pnative clean package
```

For the yml being excluded by default (if no `application*.yml`) - we could do that, the only concern is perhaps the confusion around how to override that since you'd need it both in build.args and on the mvn command right now. Whilst that is still complicated my preference would be do the 'most likely to work thing' by default.

**Comment by aclement** [comment]
We can do something with maven configuration pretty quickly, if we can agree on how we want it to be, but we'd need to add some form of generalized configuration for bti, rather than specific options related to native. Something like this would work but it is a little crude:

`AbstractBootstrapMojo.java`
```
	@Parameter
	protected Map<String,String> options;
```

And then the maven pom could say something like:
```
<configuration>
  <options>
    <spring.native.remove-yaml-support>true</spring.native.remove-yaml-support>
  </options>
</configuration>
```
Then have options available through the build context - we're all set - no need for -D to the mvn command.

That is not particularly elegant with the duplication of the opening closing key name.   Using `Properties` instead of map is feasible but still the xml is still a little ugly. Happen to learn from a maven guru on the better options.

**Comment by sdeleuze** [comment]
Yeah I will add such Maven configuration as your proposed. We can ask to Maven experts as a second step.

**Comment by sdeleuze** [comment]
I think I would prefer to use a more Spring Boot-ish approach for configuration, I am trying to implement what I have in mind.

**Comment by sdeleuze** [comment]
The Spring Boot-ish way will probably be the target, but it is too ambitious for now. For now I am implementing a regular Maven configuration like:
```
<configuration>
  <native>
    <mode>agent</mode>
    <removeYamlSupport>true</removeYamlSupport>
  </native>
</configuration>
```
