### ISSUE TITLE
Fix com.mysql.cj.LocalizedErrorMessages errors on Petclinic samples

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#505]
On `petclinic-jpa` and `petclinic-jdbc`, bundles defined in `@nativeHint` seems not taken in account by Spring AOP build plugin. This has been not detected because those samples were not correctly tested but thanks to @schauder it is now the case.

**Comment by aclement** [comment]
I have a basically working fix, however due to side effects I have a bit more work to do. Registering the bundles is no big deal, however, GraalVM will hard fail if you ask for a bundle that isn't around. That means some of our hints that aren't quite correct cause samples to fail as bundles are registered that aren't around. (example, the webflux samples ask for the LocalStrings bundle that is only in webmvc samples). Shouldn't be too much work to sort it out.

I will mention when the bundle is working I then hit a missing proxy error for `org.hibernate.query.spi.QueryImplementor`which it looks like somebody needs to add.

**Comment by aclement** [comment]
Changes are in. There are warnings in the output if hints lead to attempting to add bundles that won't work at native-image build time. 

There is still the issue I eluded to about a missing proxy for QueryImplementor being reported (for petclinic-jpa) - maybe @schauder can take a look now I've unblocked it?

**Comment by sdeleuze** [comment]
I fixed it with 4b65a683fd10b8462cbe801d33d2895b35724981 @schauder feel free to update if you want to implement it differently.
