### ISSUE TITLE
Can't easily debug application in IDE with spring-native

### ISSUE THREAD

**Issue by leccelecce** [spring-projects-experimental/spring-native#523]
0.9.0-SNAPSHOT

This is as much a question as anything. Normally, all I need to do to debug my application is `mvn clean compile` and then I can attach a debugger. Going even further, in the case of IntelliJ, the auto-build function just compiles as I edit and triggers a hot code replace in the background in many cases. Spring DevTools is also helpful here for a variety of reasons.

But with spring-native on the classpath, `NativeListener` kicks in and throws a GeneratedClassNotFoundException if spring-aot:generate hasn't been run to create the various classes. My question here is: is this really necessary? My application runs just fine without spring-native - yes I have had to adapt some of my code to support being built for native, but functionally it's pretty close. In an ideal world I would be able to develop the same way as normal, with the use of lots of IDE magic, with the heavy lifting coming in during packaging and build.

Given that this would delay how early you might catch issues, perhaps this could be opt-in e.g. set a flag in my debug profile that tells spring-native to back off? If this is something you agree with I would be happy to send a PR.

**Comment by sdeleuze** [comment]
You can put the `spring-native` dependency and `spring-aot-maven-plugin` in a dedicated profile if you prefer that, but I think we would like to try to promote a default execution on the JVM with the AOT transformation because that allow you to have some same codepath that will run on native, and given native very long compilation time we see a lot of value in that even if I agree tha the IDE experience is not yet seemless, debugging is pretty easy to setup (see https://docs.spring.io/spring-native/docs/0.9.0-SNAPSHOT/reference/#spring-aot) and works in a reliable way.

**Comment by leccelecce** [comment]
That makes sense, thank you.
