### ISSUE TITLE
More hints for @Bean with a class that has @ConfigurationProperties should be added to reflect-config.json

### ISSUE THREAD

**Issue by dsyer** [spring-projects-experimental/spring-native#577]
The discoverclient sample was broken in the sense that you could not configure `eureka.client.*` at runtime. The problem was that the JSON we generated for the `EurekaClientConfigBean` didn't include method access. So that seems like a bug in the AOT processor?

**Comment by aclement** [comment]
When I build the discovery client sample on Java11, and inspect:

```
target/test-classes/META-INF/native-image/org.springframework.aot/spring-aot/reflect-config.json
```

I see:

```
{
    "name": "org.springframework.cloud.netflix.eureka.EurekaClientConfigBean",
    "allDeclaredFields": true,
    "allDeclaredConstructors": true,
    "allDeclaredMethods": true
  },
```

How am I building things differently to you?

**Comment by aclement** [comment]
I think this is another case we were see 'advanced spring usage' in Spring Cloud that pushes on some of the current analysis techniques in areas that it does not currently support (so kinda what Dave eluded to in the first comment). I can make this work but I don't think I'm going to disturb 0.9.0 any more.

If the properties were being referred to like many other spring configurations do:
```
@EnableConfigurationProperties(RabbitProperties.class)
public class RabbitAutoConfiguration {
```

```
@EnableConfigurationProperties({ ServerProperties.class, SessionProperties.class })
public class SessionAutoConfiguration {
```

it would be fine, but because the properties here are pulled in via an `@Bean` reference, they aren't exposed with the right visibility, but there is a further follow on problem - exposing them is fine but if they don't go through the proper configuration property analysis then any nested classes or related properties classes referenced from members of the configuration properties won't be exposed properly. For this reason I'm not doing a quick hack now with 0.9 so close (it increases RSS by 4M for the discovery client sample).

**Comment by aclement** [comment]
Fixed up. When `@Bean` methods return a configuration properties object we do properties analysis and ensure access to that type (as well as complex types of any properties within it) is correct.
