### ISSUE TITLE
Document how to run Spring AOT generation when using mvn spring-boot:run

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#593]
On https://github.com/mraible/blog-oauth2/tree/spring-native I had sometimes no AOT generation leading to the `The ApplicationContext could not start as 'org.springframework.aot.StaticSpringFactories' that is generated by the Spring AOT plugin could not be found.` when running `mvn clean spring-boot:run` but I also add a strange [`DataSize` error](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#_datasize_was_unintentionally_initialized_at_build_time).

**Comment by sdeleuze** [comment]
I confirm this issue with a simpler and straightforward repro:
 - Create a new project on start.spring.io with Spring Native and in my case WebFlux
 - Run `mvn spring-boot:run`
 - `The ApplicationContext could not start as 'org.springframework.aot.StaticSpringFactories' that is generated by the Spring AOT plugin could not be found.`

When running `mvn package` or`mvn test` it works as expected.

**Comment by bclozel** [comment]
I think we're hitting a hard limitation of our current model: the Maven lifecycle and the fact that the Spring Boot plugin and the AOT plugin are completely separate make it impossible to fix.

The Spring Boot maven plugin binds the `run` Mojo at the `test-compile` phase, this means that running `spring-boot:run` executes [all phases up to that point](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html) and [then configures a default Mojo execution for it](https://maven.apache.org/guides/mini/guide-default-execution-ids.html).

We initially configured the `spring-aot:generateAot` Mojo at the `process-classes`, which worked with this case. But compiling our AOT classes to the main output directory would later fail, since tests are using this output in their classpath. This is why we moved the AOT generation to the `prepare-package` phase and the AOT test is bound to `process-test-classes`.

I think we should be able to solve this completely if the Spring Boot and Native plugins are merged in the future. In the meantime, we might have to document this workaround:

```shell
$ ./mvnw package spring-boot:run
```

I'm leaving this issue opened for now, maybe there's a way to better handle the lifecycle or separate the AOT classes to avoid merging them in the main output directory.

Note: `./gradlew bootRun` works fine since we can configure task dependencies with Gradle.

**Comment by sdeleuze** [comment]
@bclozel I would suggest we move this issue to 0.10, and create another documentation issue for indeed documenting the workaround in 0.9.1.

For 0.10, my current thinking based on your findings and what we see on Eclipse where we keep having issues with duplicated classes is that we could try to bring back `spring-aot:generateAot` to `process-classes` and make what we generate for tests purely additive to what we generate in main, with something like a `TestStaticSpringFactories` class and reusing in tests the `_FactoryProvider` generated in main.

Would that be ok from your POV?

**Comment by bclozel** [comment]
I think that the static factories class as an entry point is only half of the story. I suspect that more issues related to development lifecycle are bound to happen with Maven since we're writing to the main output directory and the test output directory.

I think we should turn this issue into a documentation one for the workaround and rethink our approach here in a different issue for 0.10.

**Comment by sdeleuze** [comment]
2 points to share:
 - Does it make more sense to recommend using `mvn package spring-boot:run` or `mvn spring-aot:generate spring-boot:run`?
 - Even if putting a Maven specific message in `GeneratedClassNotFoundExceptionFailureAnalyzer` is in theory not ideal, maybe this issue will be common enough to deserve adding something specific in the action proposed because here it is not about local configuration of the plugin and requiring to jump to the doc is maybe too much.

**Comment by bclozel** [comment]
I had a look into this and:

1. Running the `spring-aot:generate` goal does not trigger the maven lifecycle, so the `compile` phase is not triggered. In general, we should not advertize too much this goal in our docs as it won't do what people might think (i.e. "running a maven plugin goal" vs. "triggering a maven lifecycle phase"). So `mvn package spring-boot:run` is still the recommendation IMO.
2. Running `spring-boot:run` forks from the maven build thread, so there is no trace of maven classes in the `GeneratedClassNotFoundExceptionFailureAnalyzer` stacktrace.

This case is still important enough that it should be mentioned in the FailureAnalyzer and the docs should be updated. We'll do that as part of this issue.
