### ISSUE TITLE
Allow JHipster sample to compile to native

### ISSUE THREAD

**Issue by jdubois** [spring-projects-experimental/spring-native#600]
As discussed with @sdeleuze on Twitter, I created a sample JHipster project and configured it using Spring Native.

-> here's the ticket will all information on the JHipster side: https://github.com/jhipster/generator-jhipster/issues/13733

The 2 first problems are:
- The logback file makes startup fail (you can go past this by removing the file)
- There is an error concerning the HttpStatus class. As we're using Undertow, I tried to migrate to Tomcat, but that didn't help.

**Comment by sdeleuze** [comment]
Thanks Julien, let's try to see if we can make it in time for 0.9.1 otherwise we will move it to 0.9.2.

**Comment by sdeleuze** [comment]
FYI We are working on solving various issues you encountered via other issues:
 - Logback #625
 - `HttpStatus` #612
 - Make sure AOT compilation is invoked : #623 and #593

**Comment by sdeleuze** [comment]
I had a deeper look to your JHipster sample app.

After removing `logback-spring.xml` due to #625, and `@EnableJpaAuditing(auditorAwareRef = "springSecurityAuditorAware")` because not supported yet, I faced this error `Binding to target [Bindable@cc33e78 type = tech.jhipster.config.JHipsterProperties] failed`.

Spring Native is supposed to recognize `@EnableConfigurationProperties` usages and register reflection entries properly but here, I am not sure how `JHipsterProperties` is registered. I see this in `jhipster-framework` `spring.factories`:
![image](https://user-images.githubusercontent.com/141109/111614885-6a40fc80-87e0-11eb-9c14-44359c4cc2f1.png)

Could you share more context about how `JHipsterProperties` is registered and why?

**Comment by jdubois** [comment]
- `@EnableJpaAuditing(auditorAwareRef = "springSecurityAuditorAware")` should be removed anyway, this comes from my very early code and I now believe this was a bad idea.
- For `JHipsterProperties`, I believe this is also my fault -> shouldn't it be listed here, in the `spring.factories`? I thought it was the correct way to register some custom properties (and it works!), but I haven't studied that at all

**Comment by sdeleuze** [comment]
For `JHipsterProperties`, the recommended way to do it is probably to specify `@EnableConfigurationProperties(JHipsterProperties.class)` on a configuration classes imported by a `spring.factories`.

I am moving this issue to 0.9.2 since that's mostly a tracking issue for other more fine grained issues in order to have your basic sample working and since that will require update on your side for `JHipsterProperties`. Please let me know when I can test again.

**Comment by jdubois** [comment]
Oh sorry, this is probably what I did - and so listing it in spring.factories should be a mistake. I'll have a look.

**Comment by sdeleuze** [comment]
Let's continue the work and discussion on https://github.com/jhipster/generator-jhipster/issues/13733 to avoid duplication.
