### ISSUE TITLE
Custom Spring Data Elasticsearch repository fragment implementation not found when running in native

### ISSUE THREAD

**Issue by sothawo** [spring-projects-experimental/spring-native#639]
I am trying native with Spring Data Elasticsearch and am running into a problem when implementing a custom fragment for the Spring Data Elasticsearch repository.  It seems that the custom implementation class is not found (although added with `@TypeHint`).

A sample application showing this with a more detailed description can be found at https://github.com/sothawo/dataesnative

**Comment by sdeleuze** [comment]
@christophstrobl Could you please have a look to the provided sample application to qualify it?

**Comment by christophstrobl** [comment]
There seems to be an issue with picking up the component based on the naming of custom implementations. 
While we work on this issue, you can rename `PersonCustomRepositoryImp` to `PersonRepositoryImpl` which will allow it to be detected correctly. 
The provided sample app still won't work (due to missing configuration for one of the used libs), but the repository lookup won't be standing in your way any more.

**Comment by sothawo** [comment]
thanks for the info; I'll get to the next errors as soon as I see them ;-) 
The workaround is alright in this example, but wehn there are multiple custom interfaces with their implementations, it would mean to merge the impls together into one file. 
But for my case - testing out Spring Data Elasticsearch with native - this is alright for the moment.
