### ISSUE TITLE
Missing the auto-configuration of CoroutineSortingRepository

### ISSUE THREAD

**Issue by nfrankel** [spring-projects-experimental/spring-native#643]
As mentioned in [this post](https://blog.frankel.ch/kick-spring-native-tires/#missing-proxies), the auto-configuration of proxies fail on the `CoroutineSortingRepository`.

Please check [this project](https://github.com/hazelcast-demos/imperative-to-reactive/blob/native/src/main/java/org/hazelcast/cache/Person.kt#L40) for a reproducer.

**Comment by sdeleuze** [comment]
As discussed with @christophstrobl, we should probably add a Coroutines R2DBC sample and refine the processor logic accordingly.

**Comment by sdeleuze** [comment]
See also the other repro project from #735.

**Comment by sdeleuze** [comment]
The root issue is that we don't use `kotlin-reflect`, so for methods using Coroutines, the return value detected in `Object` not the real return type because that's how Coroutines are compiled at bytecode level. Our fix is specific to this Spring Data Coroutines use case, but given how popular they are, I think it is worth to have it.
