### ISSUE TITLE
Is there a way to add manually @Configuration classes to the StaticSpringFactories?

### ISSUE THREAD

**Issue by khaeghar** [spring-projects-experimental/spring-native#644]
Hi,

I've just migrated from 0.9.0-SNAPSHOT to 0.9.0, and I've added the AOT plugin.

When doing a mvn clean install, the StaticSpringFactories class is created.

With the first execution, I realized that not every @Configuration class was included in the factory, so I added:

```
<configuration>
	<buildTimePropertiesChecks>default-exclude-all</buildTimePropertiesChecks>
</configuration>
```

and that solved the problem so far.

But when I added a dependency of mine that has 2 configuration files for 2 different flavors (Reactive and Servlet), only the Reactive Config file is included in the StaticSpringFactories, making the Servlet flavor not operative.

Is there a way to manually include this class? With @NativeHint maybe? or is there another method?

**Comment by bclozel** [comment]
Hello @khaeghar 

It's not clear to me which configuration property is covered by the AOT processing and why disabling them all with `buildTimePropertiesChecks` is your only way out. This AOT configuration should be disabled by default and all configuration properties should be processed at runtime. Maybe there's a bug in our plugin setup.

Now your use case involving a custom dependency shipping support for several web variants is a different problem and we'd like to know more about this.

Could you provide a sample application showing the problem? Something minimal that we can git clone or download would be perfect. Thanks!

**Comment by khaeghar** [comment]
I'm working on the reproducer but I'm not getting the same results. Don't know what's changing since there are several layers in this project, but I'm on it.

Anyway, those classes were not the only ones that were present in the StaticSpringFactories file, there were many more of my config files there. That's not the usual behavior, right?


```
@Configuration(proxyBeanMethods = false)
@AutoConfigureAfter(AuthenticationAutoConfiguration.class)
@ConditionalOnProperty(name = { "security.enabled" }, havingValue = "true", matchIfMissing = true)
@Conditional(ServletOrNotWebCondition.class) //This condition checks if the app is servlet or not web
@EnableConfigurationProperties(WebServiceProperties.class)
@Slf4j
public class WebServiceWebAutoConfig {
```

The config file annotations looks like this. Don't know if there's something weird in there but since I'm not able to reproduce it in a separate project I'm a bit lost.

May I ask which is the procedure to include classes in the StaticSpringFactories? Or if there's some documentation about it.

**Comment by bclozel** [comment]
@khaeghar the Conditional annotations you're listing here should be supported.

Our AOT process is processing Conditional annotations and doing its best to guess whether they will match at runtime. Currently our model is incomplete and might not reflect 100% the runtime behavior in the JDK - this is why I've asked for a repro project in this case.

At build time, our AOT plugin looks at all factories declared in `spring.factories` and generates source code as `StaticSpringFactories` to register those factories without reflection. As long as factories (and in this case auto-configurations) are listed in such files, they're considered by the build plugin. In your case, it looks like it's ignored because our filtering mechanism somehow thinks that it won't be needed at runtime. Note that we're not taking a radical approach here, and that we're only assuming that the classpath of the application is fixed at build time when you're packaging the application. Maybe this assumption doesn't work in your case?

I'm afraid the AOT approach is the path we've chosen to improve our support. We got good results so far with it and we're working on improving it.

Is your project a complete Spring Boot application that's meant to be shipped and run in production, or some kind of library that can be pulled by other applications? I'm a bit curious about why an application would ship auto-configurations for both reactive and servlet variants.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by khaeghar** [comment]
Hi, I'm sorry for the tremendous delay. Right now I'm not able to provide you with the reproducer since my tries have been futile and doesn't reproduce the behavior. The actual project it's really big and the info I gave you guys is all I can give by the moment. I'll try to work on it once we come back again to the GraalVM of the project. Thanks for everything!

**Comment by sdeleuze** [comment]
Ok thanks please create a new issue later if needed.
