### ISSUE TITLE
Actuator @Endpoint registered @Bean is not available

### ISSUE THREAD

**Issue by phejl** [spring-projects-experimental/spring-native#881]
Thsi works in JVM.

**Comment by aclement** [comment]
The changes for 880 fix this too. It would be helpful to include code snippets in some of these issues to verify I'm fixing what you are describing. I've simply fixed the scenarios I was able to recreate. All expected stuff because we hadn't gone into this area yet. I've extended the scheduled-tasks sample and the actuator-webmvc sample to cover these two issues.
