### ISSUE TITLE
Remove reflection config for classes instantiated programmatically in StaticSpringFactories

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#931]
Like `DebugAgentEnvironmentPostProcessor` , `R2dbcScriptDatabaseInitializerDetector` or `LiquibaseDatabaseInitializerDetector`.

**Comment by sdeleuze** [comment]
@bclozel Any thoughts on that one?

**Comment by bclozel** [comment]
In the case of `*DatabaseInitializerDetector`, we're seeing the following behavior: our new build time infrastructure does process the `DatabaseInitializationDependencyConfigurer` and registers `DependsOnDatabaseInitializationPostProcessor` with the context. But it is that processor that loads factories at runtime, so we can remove the factories build-time processing for this case right now.

The general rule is that `ImportBeanDefinitionRegistrar` are processed at build time because they operate on the `BeanDefinitionRegistry`, but `BeanFactoryPostProcessor` are processed at runtime because they operate on bean instances directly. There are of course ways to improve that, but this enhancement has to be done in the target project directly.

Here are a few factories and how they're loaded right now:
* `FailureAnalyzer` are loaded as `SpringBootExceptionReporter` at runtime after a context failure
* same for `SpringApplicationRunListener`, `ApplicationContextInitializer` and `ApplicationListener`

We might be able to remove `AutoConfigurationImportListener` and `AutoConfigurationImportFilter` as they're dealt with in the `AutoConfigurationImportSelector` directly.

**Comment by bclozel** [comment]
Closed with f81fa35
