### ISSUE TITLE
setConnectionTimeout on RestTemplateBuilder is not Working

### ISSUE THREAD

**Issue by goafabric** [spring-projects-experimental/spring-native#954]
Imagine the following code

 final RestTemplate restTemplate = new RestTemplateBuilder()
                .setConnectTimeout(Duration.ofMillis(timeout))
                .setReadTimeout(Duration.ofMillis(timeout))
                .build();

While working in normal mode, a call inside a Native Image will crash with:
"SimpleClientHttpRequestFactory does not have a suitable setConnectTimeout method"

Would be nice if this can be fixed.

**Comment by ttddyy** [comment]
Hi,

I just checked why. 

The `RestTemplateBuilder` uses reflection to access `setConnectTimeout`/`setReadTimeout`/`setBufferRequestBody` methods on underlying `ClientHttpRequestFactory`. 

https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/web/client/RestTemplateBuilder.java#L760-L784

So those methods need some entries for `@TypeHint`/`reflect-config.json`.

**Comment by goafabric** [comment]
Yes you are right .. wouldn't have thought that this is so easy
A simple 
@TypeHint(types = org.springframework.http.client.SimpleClientHttpRequestFactory.class)

fixes the issue ... would be nice though if RestTemplateBuilder will have this out of the box ..
Thx 4 the quick support.

One more thing .. do you know why all returned classes from a RestTemplate call 
also have to be registered for Reflection manually ?
I guess because the JSON (De)Serializer creates them via Reflection ?

Quarkus currently does this automatically for everything annotated with "RegisterRestCLient"

**Comment by ttddyy** [comment]
I have created a PR to add a type hint for `SimpleClientHttpRequestFactory`.
https://github.com/spring-projects-experimental/spring-native/pull/959

> One more thing .. do you know why all returned classes from a RestTemplate call
also have to be registered for Reflection manually ?
I guess because the JSON (De)Serializer creates them via Reflection ?

Yeah, I think so.
To map the json string to the target type object, jackson should be constructing the target type dynamically unless custom (de)serializers are used.

I think one way to achieve it would be spring-aot may look for the return types from controllers and automatically register them.
Or, spring-aot may generate serializers that would convert to the target type explicitly without reflection. Just my ideas.

**Comment by goafabric** [comment]
Thank you
