### ISSUE TITLE
Add Support for @MockBean 

### ISSUE THREAD

**Issue by eiswind** [spring-projects-experimental/spring-native#975]
When I try to run a test, that uses `@MockBean` I get

```
com.oracle.svm.core.jdk.UnsupportedFeatureError: Proxy class defined by interfaces [interface org.mockito.plugins.PluginSwitch] not found. Generating proxy classes at runtime is not supported.
``` 

I could not figure out how to allow the proxy manually, but I also think it would be helpful if spring native would support this ootb.

I created a little sample that reproduces the problem at https://github.com/eiswind/mockbean-spring-native

**Comment by sdeleuze** [comment]
Hi, [as documented](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#support-spring-boot):

> Libraries generating bytecode at runtime like Mockito are not supported.

This kind of use case needs to be solved on GraalVM side before we can support it here, so maybe raise an issue asking Mockito support in https://github.com/graalvm/native-build-tools on tooling side where there is support for tests in order to allow us to have a look with GraalVM team.

**Comment by haroldlbrown** [comment]
It seems to me that [GraalVM is now supported by Mockito](https://github.com/mockito/mockito/pull/2613) and that [GraalVM in turn supports Mockito](https://github.com/graalvm/native-build-tools/issues/228).
