### ISSUE TITLE
Add scoped beans support

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#981]
`cloud-config/configserver`, `cloud-discovery/discoveryclient`, `wavefront-sleuth` and `zipkin-sleuth` samples are broken on `0.11.x`, a NPE is thrown by `org.springframework.context.bootstrap.generator.event.EventListenerMethodRegistrationGenerator.writeEventListenersRegistration(EventListenerMethodRegistrationGenerator.java:96)` because scoped beans are not supported.

See [this related PR](https://github.com/sdeleuze/spring-native/commit/1e298ccd1fafc7cd45bca22d58b7fbe7a39abb91) that fixes the NPE but not the root cause.

**Comment by snicoll** [comment]
I've pushed basic support in https://github.com/spring-projects-experimental/spring-native/commit/8f9ef08b91e9fd42f548f327f43bd09733c7cb18 but we need to take care of creating the proxies when one is required. A bean that requires one now fails in native.

**Comment by aclement** [comment]
Now unfortunately I don't know one of of a scoped proxy bean from another :) But let me describe what I see. The batch-io sample builds with 0.10 Spring Native and works as a native image, in the target classes folder we see two proxies were generated at build time to support the app in 0.10:
```
./target/classes/org/springframework/batch/core/launch/support/SimpleJobOperator$$SpringProxy$fde47779.class
./target/classes/com/example/batch/ItemReaderListener$$SpringProxy$bd3dea77.class
```

With 0.11 the exact same application is failing. The same two proxies are there:
```
./target/classes/org/springframework/batch/core/launch/support/SimpleJobOperator$$SpringProxy$fde47779.class
./target/classes/com/example/batch/ItemReaderListener$$SpringProxy$bd3dea77.class
```
but in addition on 0.11 it is looking for extra proxies for lambda clauses in the application.  This bit of code:
```
	@JobScope
	@Bean
	public ItemProcessor<Person, Person> itemProcessor() {
		return person -> new Person(person.getFirstName(), person.getLastName().toUpperCase());
	}
```
is causing this error at runtime:
```
Caused by: org.springframework.aop.framework.AopConfigException: Unexpected problem loading and instantiating proxy for target class class com.example.batch.configuration.BatchConfiguration$$Lambda$c42fa1503ed3c74f174a192774d0edc19cbfda63; nested exception is java.lang.IllegalStateException: Class proxy missing at runtime, hint required at build time: @AotProxyHint(targetClass=com.example.batch.configuration.BatchConfiguration$$Lambda$c42fa1503ed3c74f174a192774d0edc19cbfda63.class, interfaces={org.springframework.aop.scope.ScopedObject.class, java.io.Serializable.class, org.springframework.aop.framework.AopInfrastructureBean.class, org.springframework.batch.item.ItemProcessor.class})
```

My question is why is a proxy required for this lambda in 0.11 and not in 0.10? Is it because 0.10 was making a mistake and 0.11 has fixed it?
Addressing this with a hint is not trivial because the lambda class that is the superclass of the required proxy doesn't exist at build time.  The app can be reworked to use anonymous inner classes instead of lambdas but that feels wrong (even though it does work because you can then add the hint).
